# 
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret: <%= ENV["DEVISE_SECRET"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"]%>
  facebook_app: <%= ENV["FACEBOOK_APP"]%>
